/**
 * JavaScript Bundler using esbuild
 * Bundles all modules into a single file for production
 */

import esbuild from 'esbuild';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.join(__dirname, '..');
const publicDir = path.join(rootDir, 'public');
const modulesDir = path.join(publicDir, 'modules');

// Entry points
const entryPoints = [
    path.join(publicDir, 'app.js')
];

// Output file
const outFile = path.join(publicDir, 'bundle.js');

// Build options
const buildOptions = {
    entryPoints,
    bundle: true,
    outfile: outFile,
    minify: true,
    sourcemap: true,
    target: ['es2020'],
    format: 'esm',
    platform: 'browser',
    loader: {
        '.js': 'js'
    },
    banner: {
        js: `// GerardOS Private Dashboard - Bundled with esbuild
// Version: ${new Date().toISOString()}
// Do not edit this file directly - edit source files in modules/
`
    },
    logLevel: 'info'
};

async function build() {
    console.log('🚀 Starting JavaScript build...');
    
    try {
        // Clean previous build
        try {
            await fs.unlink(outFile);
            await fs.unlink(`${outFile}.map`);
        } catch (e) {
            // Ignore if files don't exist
        }
        
        // Build
        const result = await esbuild.build(buildOptions);
        
        console.log('✅ JavaScript build completed successfully!');
        console.log(`   Output: ${outFile}`);
        console.log(`   Size: ${(await fs.stat(outFile)).size / 1024} KB`);
        
        return result;
        
    } catch (error) {
        console.error('❌ JavaScript build failed:', error);
        process.exit(1);
    }
}

// Run build
build().catch(() => process.exit(1));
